--DATABASE OLUÞTURMA

CREATE DATABASE HAFTA2

-- ÝLGÝLÝ  DATABASE'E BAÐLANMA
USE HAFTA2

--PRODUCT  TABLOSU OLUÞTURMA

CREATE TABLE [dbo].[Product](
	[Id] [INT] IDENTITY(1,1) NOT NULL,
	[Code] [NVARCHAR](50) NULL,
	[Name] [NVARCHAR](50) NULL,
	[Price] [DECIMAL](18, 2) NULL,
	[CategoryId] [INT] NOT NULL,
 CONSTRAINT [PK_Product] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
));

--CATEGORY TABLOSU OLUÞTURMA

CREATE TABLE [dbo].[Category](
	[Id] [INT] IDENTITY(1,1) NOT NULL,
	[Name] [NVARCHAR](50) NULL,
 CONSTRAINT [PK_Category] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
));

-- PRODUCT VE CATEGORY TABLOSU ARASINDAKÝ ÝLÝÞKÝYÝ OLUÞTURMA

ALTER TABLE [dbo].[Product]  WITH CHECK ADD  CONSTRAINT [FK_Product_Category] FOREIGN KEY([CategoryId])
REFERENCES [dbo].[Category] ([Id]);

--PRODUCTFEATURE TABLOSUNU OLUÞTURMA

CREATE TABLE [dbo].[ProductFeature](
	[Id] [INT] NOT NULL,
	[Color] [NVARCHAR](10) NULL,
	[Widht] [INT] NULL,
	[Height] [INT] NULL,
 CONSTRAINT [PK_ProductFeature] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
));

--PRODUCTFEATURE ÝLE PRODUCT TABLOSU ARASINDAKÝ ÝLÝÞKÝYÝ  OLUÞTURMA

ALTER TABLE [dbo].[ProductFeature]  WITH CHECK ADD  CONSTRAINT [FK_ProductFeature_Product] FOREIGN KEY([Id])
REFERENCES [dbo].[Product] ([Id]);


